pipeline {
    agent any

    stages {
        stage("Set environment") {
            steps {
                echo "Copy require file to pipeline folder"
                sh 'cp /var/jenkins_home/util/back/application.yml ./back/src/main/resources/application.yml'
                sh 'cp /var/jens_home/util/back/.env ./back/.env'
            }
        }

        stage('Docker Build') {
            steps {
                dir('back/') {
                    sh 'docker build -t back_img:latest .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker rm -f back_container'
                sh 'docker run -d --env-file ./back/.env --name back_container -p 8080:8080 -u root back_img:latest'
            }
        }

        stage('Finish') {
            steps {
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
            }
        }
    }
}
