import "./globals.css";
import ThemeRegistry from "../styles/ThemeRegistry";
import ServiceWorker from "./ServiceWorker";

import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PWATest",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
  themeColor: "#f69435",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ServiceWorker />
      <ThemeRegistry>
        <body
          className={inter.className}
          style={{ backgroundColor: "#f2f2f2" }}
        >
          <Box
            sx={{
              height: "100vh",
              maxWidth: "480px",
              margin: "auto",
              backgroundColor: "#fff",
              position: "relative",
            }}
          >
            {children}
          </Box>
        </body>
      </ThemeRegistry>
    </html>
  );
}
