import './globals.css';
import ThemeRegistry from '../styles/ThemeRegistry';
import ServiceWorker from './ServiceWorker';

import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Petdio',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
  themeColor: '#8758FF',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ServiceWorker />
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-4HGPR7ZWG3"
      />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-4HGPR7ZWG3');
        `}
      </Script>
      <ThemeRegistry>
        <body
          className={inter.className}
          style={{ backgroundColor: '#f2f2f2' }}
        >
          <Box
            sx={{
              height: '100vh',
              maxWidth: '480px',
              margin: 'auto',
              backgroundColor: '#fff',
            }}
          >
            {children}
          </Box>
        </body>
      </ThemeRegistry>
    </html>
  );
}
