pipeline {
	agent any
	stages {
		stage('Docker Build') {
			steps {
				dir('front/') {
					sh 'docker build -t front_img:latest .'
				}
			}
		}

		stage('Deploy') {
			steps{
				sh 'docker rm -f front_container'
				sh 'docker run -d --name front_container --network deploy -p 3000:3000 -u root	front_img:latest'
				}
		}

		stage('Docker clear') {
			steps{
				sh 'docker system prune -f'
			}
		}
	}
}