pipeline {
	agent any
	stages {
        stage("Set environment") {
            steps {
                echo "Copy require file to pipeline folder"
                sh 'cp /var/jenkins_home/util/front/develop/.env.local ./front/.env.local'
            }
        }

		stage('Docker Build') {
			steps {
				dir('front/') {
					sh 'docker build -t front_dev_img:latest .'
				}
			}
		}

		stage('Deploy') {
			steps{
				// master랑 다름 
				sh 'docker rm -f front_dev_container'
				sh 'docker run -d --env-file ./front/.env.local --name front_dev_container --network deploy -p 3001:3000 -u root	front_dev_img:latest'
				}
		}

		stage('Docker clear') {
			steps{
				sh 'docker system prune -f'
			}
		}
	}
}