export const dogBreedList = [
  { label: "고든 세터 " },
  { label: "코통 드 튈레아르 " },
  { label: "골든두들 " },
  { label: "골든 리트리버 " },
  { label: "그레이트 데인 " },
  { label: "그레이트 스위스 마운틴 도그 " },
  { label: "그레이트 피레니즈 " },
  { label: "그레이 하운드 " },
  { label: "그린란드견 " },
  { label: "글렌 오브 이말 테리어 " },
  { label: "기슈견 " },
  { label: "나폴리탄 마스티프 " },
  { label: "노위지언 부훈트 " },
  { label: "노르웨이 엘크 하운드 " },
  { label: "노리치 테리어 " },
  { label: "노바스코샤 덕 톨링 레트리버 " },
  { label: "노퍽 테리어 " },
  { label: "뉴펀들랜드 " },
  { label: "닥스훈트 " },
  { label: "달마시안 " },
  { label: "댄디 딘몬트 테리어 " },
  { label: "도고 까나리오 " },
  { label: "도고 아르헨티노 " },
  { label: "도그 드 보르도 " },
  { label: "도베르만 핀셔 " },
  { label: "도사견 " },
  { label: "동경이 " },
  { label: "라고토 로마뇰로 " },
  { label: "라사압소 " },
  { label: "라페이로 도 알렌테조 " },
  { label: "라포니안 허더 " },
  { label: "래브라도 리트리버 " },
  { label: "레온베르거 " },
  { label: "레이크랜드 테리어 " },
  { label: "로디지아 리지백 " },
  { label: "루이지애나 레오파드 도그(카타훌라) " },
  { label: "로첸 " },
  { label: "로트바일러 " },
  { label: "마스티프 " },
  { label: "맨체스터 테리어 " },
  { label: "말티즈 " },
  { label: "미니어처 불 테리어 " },
  { label: "미니어처 슈나우저 " },
  { label: "미니어처 핀셔 " },
  { label: "말티푸 " },
  { label: "바센지 " },
  { label: "바셋 하운드 " },
  { label: "버니즈 마운틴 도그 " },
  { label: "베들링턴 테리어 " },
  { label: "발바리 " },
  { label: "벨기에 말리노이즈 " },
  { label: "벨기에 테뷰런 " },
  { label: "벨지안 그리펀 " },
  { label: "벨지언 쉽독 (벨지언 셰퍼드) " },
  { label: "보더콜리 " },
  { label: "보더 테리어 " },
  { label: "보르도 마스티프 " },
  { label: "보르조이 " },
  { label: "보스롱 " },
  { label: "보스턴 테리어 " },
  { label: "복서 " },
  { label: "볼로네즈 " },
  { label: "부르불 " },
  { label: "부비에 데 플랑드르 " },
  { label: "불개 " },
  { label: "불도그 " },
  { label: "불리 쿠타 " },
  { label: "불 마스티프 " },
  { label: "불 테리어 " },
  { label: "브뤼셀 그리펀 " },
  { label: "브리어드 " },
  { label: "브리타니 " },
  { label: "블랙 러시안 테리어 " },
  { label: "블랙 앤드 탄 쿤하운드 " },
  { label: "블러드 하운드 " },
  { label: "비글 " },
  { label: "비숑 프리제 " },
  { label: "비어디드 콜리 " },
  { label: "비즐라 " },
  { label: "빠삐용 " },
  { label: "사모예드 " },
  { label: "사플라니낙 " },
  { label: "살루키 " },
  { label: "삽살개 " },
  { label: "샤페이 " },
  { label: "서식스 스패니얼 " },
  { label: "세인트 버나드 " },
  { label: "셰틀랜드 쉽독 " },
  { label: "소프트 코티드 휘튼 테리어 " },
  { label: "솔로이츠 쿠인틀레 " },
  { label: "스무드 폭스 테리어 " },
  { label: "스웨디시 발훈트 " },
  { label: "스카이 테리어 " },
  { label: "스코티시 디어하운드 " },
  { label: "스코티시 테리어 " },
  { label: "스키퍼키 " },
  { label: "스태퍼드셔 불 테리어 " },
  { label: "스탠더드 슈나우저 " },
  { label: "스패니시 그레이 하운드 " },
  { label: "스패니시 마스티프 " },
  { label: "스피노네 이탈리아노 " },
  { label: "스피츠 " },
  { label: "시고르자브종 " },
  { label: "시바 이누 " },
  { label: "시베리언 허스키 " },
  { label: "시추 " },
  { label: "시코쿠견 " },
  { label: "실리엄 테리어 " },
  { label: "실키 테리어 " },
  { label: "아나톨리아 셰퍼드 " },
  { label: "아메리칸 불도그 " },
  { label: "아메리칸 불리 " },
  { label: "아메리칸 스태퍼드셔 테리어 " },
  { label: "아메리칸 아키다 " },
  { label: "아메리칸 에스키모 도그 " },
  { label: "아메리칸 인디언 도그 " },
  { label: "아메리칸 워터 스패니얼 " },
  { label: "아메리칸 코커 스패니얼 " },
  { label: "아메리칸 폭스하운드 " },
  { label: "아이디 " },
  { label: "아이리시 소프트코티드 휘튼 테리어 " },
  { label: "아이리시 레드 앤드 화이트 세터 " },
  { label: "아이리시 세터 " },
  { label: "아이리시 울프 하운드 " },
  { label: "아이리시 워터 스패니얼 " },
  { label: "아이리시 테리어 " },
  { label: "아키타 " },
  { label: "아펜핀셔 " },
  { label: "아프간 하운드 " },
  { label: "알래스칸 맬러뮤트 " },
  { label: "알래스칸 클리카이 " },
  { label: "에스트렐라 마운틴 독 " },
  { label: "에어데일 테리어 " },
  { label: "오브차카 " },
  { label: "오스트레일리언 실키 테리어 " },
  { label: "오스트레일리언 켈피 " },
  { label: "오스트레일리언 셰퍼드 " },
  { label: "오스트레일리언 캐틀 도그 " },
  { label: "오스트레일리언 테리어 " },
  { label: "오터 하운드 " },
  { label: "올드 잉글리시 쉽독 " },
  { label: "와이머라너 " },
  { label: "와이어 폭스 테리어 " },
  { label: "와이어헤어드 포인팅 그리펀 " },
  { label: "야쿠탄 라이카 " },
  { label: "요크셔 테리어 " },
  { label: "웨스트 하이랜드 화이트테리어 " },
  { label: "웰시 스프링어 스패니얼 " },
  { label: "웰시 코기 " },
  { label: "웰시 테리어 " },
  { label: "이비전 하운드 " },
  { label: "이탤리언 그레이하운드 " },
  { label: "잉글리시 세터 " },
  { label: "잉글리시 스프링어 스패니얼 " },
  { label: "잉글리시 코커 스패니얼 " },
  { label: "잉글리시 토이 스패니얼 " },
  { label: "잉글리시 폭스하운드 " },
  { label: "자이언트 슈나우저 " },
  { label: "재패니즈 친 " },
  { label: "재패니즈 스피츠 " },
  { label: "잭 러셀 테리어 " },
  { label: "저먼 셰퍼드 " },
  { label: "저먼 쇼트헤어드 포인터 " },
  { label: "저먼 와이어헤어드 포인터 " },
  { label: "저먼 핀셔 " },
  { label: "저먼 헌팅 테리어 " },
  { label: "제주개 " },
  { label: "진돗개 " },
  { label: "차우차우 " },
  { label: "차이니즈 샤페이 " },
  { label: "차이니즈 크레스티드 " },
  { label: "체서피크 베이 레트리버 " },
  { label: "체코슬로바키아 늑대개 " },
  { label: "치와와 " },
  { label: "카네 코르소 " },
  { label: "카디건 웰시 코기 " },
  { label: "카발리에 킹 찰스 스파니엘 " },
  { label: "캉갈 " },
  { label: "컬리코티드 레트리버 " },
  { label: "케리 블루 테리어 " },
  { label: "케언 테리어 " },
  { label: "케이넌 도그 " },
  { label: "케이스혼트 " },
  { label: "코리안 마스티프 " },
  { label: "코몬도르 " },
  { label: "코커 스패니얼 " },
  { label: "콜리 " },
  { label: "쿠바스 " },
  { label: "쿠이커혼제 " },
  { label: "클럼버 스패니얼 " },
  { label: "토이 폭스 테리어 " },
  { label: "티베탄 마스티프 " },
  { label: "티베탄 스패니얼 " },
  { label: "티베탄 테리어 " },
  { label: "파라오 하운드 " },
  { label: "파슨 러셀 테리어 " },
  { label: "패터데일 테리어 " },
  { label: "퍼그 " },
  { label: "페키니즈 " },
  { label: "펨브록 웰시 코기 " },
  { label: "포투기즈 워터 도그 " },
  { label: "포메라니안 " },
  { label: "포인터 " },
  { label: "폭스 테리어 " },
  { label: "폴리시 롤런드 시프도그 " },
  { label: "폼피츠 " },
  { label: "푸들 " },
  { label: "푸미 " },
  { label: "풀리 " },
  { label: "풍산개 " },
  { label: "프렌치 불도그 " },
  { label: "프티 바세 그리퐁 방댕 " },
  { label: "플랫코티드 레트리버 " },
  { label: "플롯 하운드 " },
  { label: "피니시 스피츠 " },
  { label: "피레니언 마스티프 " },
  { label: "피레니언 쉽독 " },
  { label: "피레니언 셰퍼드 " },
  { label: "필드 스패니얼 " },
  { label: "필라 브라질레이로 " },
  { label: "핏 불 테리어 " },
  { label: "해리어 " },
  { label: "하바니즈 " },
  { label: "홋카이도 이누 " },
  { label: "휘핏 " },
];

export const catBreedList = [
  { label: "노르웨이 숲 " },
  { label: "네벨룽 " },
  { label: "네바 마스커레이드 " },
  { label: "데본렉스 " },
  { label: "도메스틱 숏헤어/도메스틱 롱헤어 " },
  { label: "돈스코이/돈스핑크스 " },
  { label: "라가머핀 " },
  { label: "랙돌 " },
  { label: "러시안 블루 " },
  { label: "라이코이 " },
  { label: "라팜 " },
  { label: "맹크스 " },
  { label: "메인쿤 " },
  { label: "먼치킨 " },
  { label: "미뉴에트 " },
  { label: "발리니즈 " },
  { label: "버만 " },
  { label: "버미즈 " },
  { label: "벵갈 " },
  { label: "봄베이 " },
  { label: "브리티시 쇼트헤어 " },
  { label: "브리티시 롱헤어 " },
  { label: "버밀라 " },
  { label: "시베리안 " },
  { label: "샴 " },
  { label: "샤트룩스 " },
  { label: "셀커크 렉스 " },
  { label: "소말리 " },
  { label: "스코티시 폴드 " },
  { label: "스코티시 스트레이트 " },
  { label: "스핑크스 " },
  { label: "싱가푸라 " },
  { label: "스노우슈 " },
  { label: "사바나 " },
  { label: "소코케 " },
  { label: "아라비안 마우 " },
  { label: "아메리칸 밥테일 " },
  { label: "아메리칸 쇼트헤어 " },
  { label: "아메리칸 와이어헤어 " },
  { label: "아메리칸 컬 " },
  { label: "아비시니안 " },
  { label: "오리엔탈 쇼트헤어 " },
  { label: "오리엔탈 롱헤어 " },
  { label: "오시캣 " },
  { label: "유러피안 " },
  { label: "유러피안버미즈 " },
  { label: "이집션마우 " },
  { label: "엑조틱 " },
  { label: "재패니즈 밥테일 " },
  { label: "쵸시 " },
  { label: "카오마니 " },
  { label: "컬러포인트쇼트헤어 " },
  { label: "코니시 렉스 " },
  { label: "코랫 " },
  { label: "쿠리리안 밥테일 " },
  { label: "킴릭 " },
  { label: "타이 " },
  { label: "터키시 반 " },
  { label: "터키시 앙고라 " },
  { label: "통키니즈 " },
  { label: "토이거 " },
  { label: "토이밥 " },
  { label: "페르시안 " },
  { label: "픽시 밥 " },
  { label: "피터볼드 " },
  { label: "하바나브라운 " },
  { label: "히말라얀 " },
];
