export const dogBreedList = [
  { label: '고든 세터', value: 'Golden Setter' },
  { label: '코통 드 튈레아르', value: 'Coton de Tulear' },
  { label: '골든두들', value: 'Goldendoodle' },
  { label: '골든 리트리버', value: 'Golden Retriever' },
  { label: '그레이트 데인', value: 'Great Dane' },
  { label: '그레이트 스위스 마운틴 도그', value: 'Great Swiss Mountain Dog' },
  { label: '그레이트 피레니즈', value: 'Great Pyrenees' },
  { label: '그레이 하운드', value: 'Greyhound' },
  { label: '그린란드견', value: 'Greenland Dog' },
  { label: '글렌 오브 이말 테리어', value: 'Glen of Imaal Terrier' },
  { label: '기슈견', value: 'Kishu Ken' },
  { label: '나폴리탄 마스티프', value: 'Neapolitan Mastiff' },
  { label: '노위지언 부훈트', value: 'Norwegian Buhund' },
  { label: '노르웨이 엘크 하운드', value: 'Norwegian Elkhound' },
  { label: '노리치 테리어', value: 'Norwich Terrier' },
  {
    label: '노바스코샤 덕 톨링 레트리버',
    value: 'Nova Scotia Duck Tolling Retriever',
  },
  { label: '노퍽 테리어', value: 'Norfolk Terrier' },
  { label: '뉴펀들랜드', value: 'Newfoundland' },
  { label: '닥스훈트', value: 'Dachshund' },
  { label: '달마시안', value: 'Dalmatian' },
  { label: '댄디 딘몬트 테리어', value: 'Dandie Dinmont Terrier' },
  { label: '도고 까나리오', value: 'Dogo Canario' },
  { label: '도고 아르헨티노', value: 'Dogo Argentino' },
  { label: '도그 드 보르도', value: 'Dogue de Bordeaux' },
  { label: '도베르만 핀셔', value: 'Doberman Pinscher' },
  { label: '도사견', value: 'Tosa' },
  { label: '동경이', value: 'Akita' },
  { label: '라고토 로마뇰로', value: 'Lagotto Romagnolo' },
  { label: '라사압소', value: 'Lhasa Apso' },
  { label: '라페이로 도 알렌테조', value: 'Lafayette De Alentejo' },
  { label: '라포니안 허더', value: 'Laponian Herder' },
  { label: '래브라도 리트리버', value: 'Labrador Retriever' },
  { label: '레온베르거', value: 'Leonberger' },
  { label: '레이크랜드 테리어', value: 'Lakeland Terrier' },
  { label: '로디지아 리지백', value: 'Rhodesian Ridgeback' },
  {
    label: '루이지애나 레오파드 도그(카타훌라)',
    value: 'Louisiana Leopard Dog (Catahoula)',
  },
  { label: '로첸', value: 'Lowchen' },
  { label: '로트바일러', value: 'Rottweiler' },
  { label: '마스티프', value: 'Mastiff' },
  { label: '맨체스터 테리어', value: 'Manchester Terrier' },
  { label: '말티즈', value: 'Maltese' },
  { label: '미니어처 불 테리어', value: 'Miniature Bull Terrier' },
  { label: '미니어처 슈나우저', value: 'Miniature Schnauzer' },
  { label: '미니어처 핀셔', value: 'Miniature Pinscher' },
  { label: '말티푸', value: 'Maltipoo' },
  { label: '바센지', value: 'Basenji' },
  { label: '바셋 하운드', value: 'Basset Hound' },
  { label: '버니즈 마운틴 도그', value: 'Bernese Mountain Dog' },
  { label: '베들링턴 테리어', value: 'Bedlington Terrier' },
  { label: '발바리', value: 'Barbet' },
  { label: '벨기에 말리노이즈', value: 'Belgian Malinois' },
  { label: '벨기에 테뷰런', value: 'Belgian Tervuren' },
  { label: '벨지안 그리펀', value: 'Belgian Griffon' },
  {
    label: '벨지언 쉽독 (벨지언 셰퍼드)',
    value: 'Belgian Sheepdog (Belgian Shepherd)',
  },
  { label: '보더콜리', value: 'Border Collie' },
  { label: '보더 테리어', value: 'Border Terrier' },
  { label: '보르도 마스티프', value: 'Bordeaux Mastiff' },
  { label: '보르조이', value: 'Borzoi' },
  { label: '보스롱', value: 'Bosnian Coarse-haired Hound' },
  { label: '보스턴 테리어', value: 'Boston Terrier' },
  { label: '복서', value: 'Boxer' },
  { label: '볼로네즈', value: 'Bolognese' },
  { label: '부르불', value: 'Bouledogue' },
  { label: '부비에 데 플랑드르', value: 'Bouvier des Flandres' },
  { label: '불개', value: 'Bulldog' },
  { label: '불도그', value: 'Bulldog' },
  { label: '불리 쿠타', value: 'Bali Kutta' },
  { label: '불 마스티프', value: 'Bullmastiff' },
  { label: '불 테리어', value: 'Bull Terrier' },
  { label: '브뤼셀 그리펀', value: 'Brussels Griffon' },
  { label: '브리어드', value: 'Briard' },
  { label: '브리타니', value: 'Brittany' },
  { label: '블랙 러시안 테리어', value: 'Black Russian Terrier' },
  { label: '블랙 앤드 탄 쿤하운드', value: 'Black and Tan Coonhound' },
  { label: '블러드 하운드', value: 'Bloodhound' },
  { label: '비글', value: 'Beagle' },
  { label: '비숑 프리제', value: 'Bichon Frise' },
  { label: '비어디드 콜리', value: 'Bearded Collie' },
  { label: '비즐라', value: 'Bisben' },
  { label: '빠삐용', value: 'Papillon' },
  { label: '사모예드', value: 'Samoyed' },
  { label: '사플라니낙', value: 'Schapendoes' },
  { label: '살루키', value: 'Saluki' },
  { label: '삽살개', value: 'Sapsali' },
  { label: '샤페이', value: 'Shar Pei' },
  { label: '서식스 스패니얼', value: 'Sesamee Spaniel' },
  { label: '세인트 버나드', value: 'Saint Bernard' },
  { label: '셰틀랜드 쉽독', value: 'Shetland Sheepdog' },
  { label: '소프트 코티드 휘튼 테리어', value: 'Soft Coated Wheaten Terrier' },
  { label: '솔로이츠 쿠인틀레', value: 'Slovensky Cuvac' },
  { label: '스무드 폭스 테리어', value: 'Smooth Fox Terrier' },
  { label: '스웨디시 발훈트', value: 'Swedish Vallhund' },
  { label: '스카이 테리어', value: 'Skye Terrier' },
  { label: '스코티시 디어하운드', value: 'Scottish Deerhound' },
  { label: '스코티시 테리어', value: 'Scottish Terrier' },
  { label: '스키퍼키', value: 'Schipperke' },
  { label: '스태퍼드셔 불 테리어', value: 'Staffordshire Bull Terrier' },
  { label: '스탠더드 슈나우저', value: 'Standard Schnauzer' },
  { label: '스패니시 그레이 하운드', value: 'Spanish Greyhound' },
  { label: '스패니시 마스티프', value: 'Spanish Mastiff' },
  { label: '스피노네 이탈리아노', value: 'Spinone Italiano' },
  { label: '스피츠', value: 'Spitz' },
  { label: '세구지오', value: 'Segugio' },
  { label: '시바 이누', value: 'Shiba Inu' },
  { label: '시베리언 허스키', value: 'Siberian Husky' },
  { label: '시추', value: 'Shih Tzu' },
  { label: '시코쿠견', value: 'Shikoku' },
  { label: '실리엄 테리어', value: 'Silky Terrier' },
  { label: '실키 테리어', value: 'Silky Terrier' },
  { label: '아나톨리아 셰퍼드', value: 'Anatolian Shepherd Dog' },
  { label: '아메리칸 불도그', value: 'American Bulldog' },
  { label: '아메리칸 불리', value: 'American Bully' },
  {
    label: '아메리칸 스태퍼드셔 테리어',
    value: 'American Staffordshire Terrier',
  },
  { label: '아메리칸 아키다', value: 'American Akita' },
  { label: '아메리칸 에스키모 도그', value: 'American Eskimo Dog' },
  { label: '아메리칸 인디언 도그', value: 'American Indian Dog' },
  { label: '아메리칸 워터 스패니얼', value: 'American Water Spaniel' },
  { label: '아메리칸 코커 스패니얼', value: 'American Cocker Spaniel' },
  { label: '아메리칸 폭스하운드', value: 'American Foxhound' },
  { label: '아이디', value: 'Ibizan Hound' },
  {
    label: '아이리시 소프트코티드 휘튼 테리어',
    value: 'Irish Soft Coated Wheaten Terrier',
  },
  {
    label: '아이리시 레드 앤드 화이트 세터',
    value: 'Irish Red and White Setter',
  },
  { label: '아이리시 세터', value: 'Irish Setter' },
  { label: '아이리시 울프 하운드', value: 'Irish Wolfhound' },
  { label: '아이리시 워터 스패니얼', value: 'Irish Water Spaniel' },
  { label: '아이리시 테리어', value: 'Irish Terrier' },
  { label: '아키타', value: 'Akita' },
  { label: '아펜핀셔', value: 'Affenpinscher' },
  { label: '아프간 하운드', value: 'Afghan Hound' },
  { label: '알래스칸 맬러뮤트', value: 'Alaskan Malamute' },
  { label: '알래스칸 클리카이', value: 'Alaskan Klee Kai' },
  { label: '에스트렐라 마운틴 독', value: 'Estrela Mountain Dog' },
  { label: '에어데일 테리어', value: 'Airedale Terrier' },
  { label: '오브차카', value: 'Afghan Hound' },
  { label: '오스트레일리언 실키 테리어', value: 'Australian Silky Terrier' },
  { label: '오스트레일리언 켈피', value: 'Australian Kelpie' },
  { label: '오스트레일리언 셰퍼드', value: 'Australian Shepherd' },
  { label: '오스트레일리언 캐틀 도그', value: 'Australian Cattle Dog' },
  { label: '오스트레일리언 테리어', value: 'Australian Terrier' },
  { label: '오터 하운드', value: 'Otterhound' },
  { label: '올드 잉글리시 쉽독', value: 'Old English Sheepdog' },
  { label: '와이머라너', value: 'Weimaraner' },
  { label: '와이어 폭스 테리어', value: 'Wire Fox Terrier' },
  { label: '와이어헤어드 포인팅 그리펀', value: 'Wirehaired Pointing Griffon' },
  { label: '야쿠탄 라이카', value: 'Yakutian Laika' },
  { label: '요크셔 테리어', value: 'Yorkshire Terrier' },
  {
    label: '웨스트 하이랜드 화이트테리어',
    value: 'West Highland White Terrier',
  },
  { label: '웰시 스프링어 스패니얼', value: 'Welsh Springer Spaniel' },
  { label: '웰시 코기', value: 'Welsh Corgi' },
  { label: '웰시 테리어', value: 'Welsh Terrier' },
  { label: '이비전 하운드', value: 'Ibizan Hound' },
  { label: '이탤리언 그레이하운드', value: 'Italian Greyhound' },
  { label: '잉글리시 세터', value: 'English Setter' },
  { label: '잉글리시 스프링어 스패니얼', value: 'English Springer Spaniel' },
  { label: '잉글리시 코커 스패니얼', value: 'English Cocker Spaniel' },
  { label: '잉글리시 토이 스패니얼', value: 'English Toy Spaniel' },
  { label: '잉글리시 폭스하운드', value: 'English Foxhound' },
  { label: '자이언트 슈나우저', value: 'Giant Schnauzer' },
  { label: '재패니즈 친', value: 'Japanese Chin' },
  { label: '재패니즈 스피츠', value: 'Japanese Spitz' },
  { label: '잭 러셀 테리어', value: 'Jack Russell Terrier' },
  { label: '저먼 셰퍼드', value: 'German Shepherd' },
  { label: '저먼 쇼트헤어드 포인터', value: 'German Shorthaired Pointer' },
  { label: '저먼 와이어헤어드 포인터', value: 'German Wirehaired Pointer' },
  { label: '저먼 핀셔', value: 'German Pinscher' },
  { label: '저먼 헌팅 테리어', value: 'German Hunting Terrier' },
  { label: '제주개', value: 'Jindo' },
  { label: '진돗개', value: 'Jindo' },
  { label: '차우차우', value: 'Chow Chow' },
  { label: '차이니즈 샤페이', value: 'Chinese Shar-Pei' },
  { label: '차이니즈 크레스티드', value: 'Chinese Crested' },
  { label: '체서픽 베이 레트리버', value: 'Chesapeake Bay Retriever' },
  { label: '체코슬로바키아 늑대개', value: 'Czechoslovakian Wolfdog' },
  { label: '치와와', value: 'Chihuahua' },
  { label: '카네 코르소', value: 'Cane Corso' },
  { label: '카디건 웰시 코기', value: 'Cardigan Welsh Corgi' },
  {
    label: '카발리에 킹 찰스 스파니엘',
    value: 'Cavalier King Charles Spaniel',
  },
  { label: '캉갈', value: 'Kangal' },
  { label: '컬리코티드 레트리버', value: 'Curly-Coated Retriever' },
  { label: '케리 블루 테리어', value: 'Kerry Blue Terrier' },
  { label: '케언 테리어', value: 'Cairn Terrier' },
  { label: '케이넌 도그', value: 'Canaan Dog' },
  { label: '케이스혼트', value: 'Kai Ken' },
  { label: '코리안 마스티프', value: 'Korean Mastiff' },
  { label: '코몬도르', value: 'Komondor' },
  { label: '코커 스패니얼', value: 'Cocker Spaniel' },
  { label: '콜리', value: 'Collie' },
  { label: '쿠바스', value: 'Cuban Mastiff' },
  { label: '쿠이커혼제', value: 'Kishu Ken' },
  { label: '클럼버 스패니얼', value: 'Clumber Spaniel' },
  { label: '토이 폭스 테리어', value: 'Toy Fox Terrier' },
  { label: '티베탄 마스티프', value: 'Tibetan Mastiff' },
  { label: '티베탄 스패니얼', value: 'Tibetan Spaniel' },
  { label: '티베탄 테리어', value: 'Tibetan Terrier' },
  { label: '파라오 하운드', value: 'Pharaoh Hound' },
  { label: '파슨 러셀 테리어', value: 'Parson Russell Terrier' },
  { label: '패터데일 테리어', value: 'Patterdale Terrier' },
  { label: '퍼그', value: 'Pug' },
  { label: '페키니즈', value: 'Pekingese' },
  { label: '펨브록 웰시 코기', value: 'Pembroke Welsh Corgi' },
  { label: '포투기즈 워터 도그', value: 'Portuguese Water Dog' },
  { label: '포메라니안', value: 'Pomeranian' },
  { label: '포인터', value: 'Pointer' },
  { label: '폭스 테리어', value: 'Fox Terrier' },
  { label: '폴리시 롤런드 시프도그', value: 'Polish Lowland Sheepdog' },
  { label: '폼피츠', value: 'Pomsky' },
  { label: '푸들', value: 'Poodle' },
  { label: '푸미', value: 'Pumi' },
  { label: '풀리', value: 'Puli' },
  { label: '풍산개', value: 'Poongsan Dog' },
  { label: '프렌치 불도그', value: 'French Bulldog' },
  { label: '프티 바세 그리퐁 방댕', value: 'Petit Basset Griffon Vendeen' },
  { label: '플랫코티드 레트리버', value: 'Flat-Coated Retriever' },
  { label: '플롯 하운드', value: 'Plott Hound' },
  { label: '피니시 스피츠', value: 'Finnish Spitz' },
  { label: '피레니언 마스티프', value: 'Pyrenean Mastiff' },
  { label: '피레니언 쉽독', value: 'Pyrenean Sheepdog' },
  { label: '피레니언 셰퍼드', value: 'Pyrenean Shepherd' },
  { label: '필드 스패니얼', value: 'Field Spaniel' },
  { label: '필라 브라질레이로', value: 'Fila Brasileiro' },
  { label: '핏 불 테리어', value: 'Pit Bull Terrier' },
  { label: '해리어', value: 'Harrier' },
  { label: '하바니즈', value: 'Havanese' },
  { label: '홋카이도 이누', value: 'Hokkaido Inu' },
  { label: '휘핏', value: 'Whippet' },
];

export const catBreedList = [
  { label: '노르웨이 숲', value: 'Norwegian Forest' },
  { label: '네벨룽', value: 'Nebelung' },
  { label: '네바 마스커레이드', value: 'Neva Masquerade' },
  { label: '데본렉스', value: 'Devon Rex' },
  {
    label: '도메스틱 숏헤어/도메스틱 롱헤어',
    value: 'Domestic Shorthair/Domestic Longhair',
  },
  { label: '돈스코이/돈스핑크스', value: 'Don Sphynx/Donskoy' },
  { label: '라가머핀', value: 'Ragamuffin' },
  { label: '랙돌', value: 'Ragdoll' },
  { label: '러시안 블루', value: 'Russian Blue' },
  { label: '라이코이', value: 'Lykoi' },
  { label: '라팜', value: 'LaPerm' },
  { label: '맹크스', value: 'Manx' },
  { label: '메인쿤', value: 'Maine Coon' },
  { label: '먼치킨', value: 'Munchkin' },
  { label: '미뉴에트', value: 'Minuet' },
  { label: '발리니즈', value: 'Balinese' },
  { label: '버만', value: 'Burmese' },
  { label: '버미즈', value: 'Burmilla' },
  { label: '벵갈', value: 'Bengal' },
  { label: '봄베이', value: 'Bombay' },
  { label: '브리티시 쇼트헤어', value: 'British Shorthair' },
  { label: '브리티시 롱헤어', value: 'British Longhair' },
  { label: '버밀라', value: 'Burmilla' },
  { label: '시베리안', value: 'Siberian' },
  { label: '샴', value: 'Siamese' },
  { label: '샤트룩스', value: 'Chartreux' },
  { label: '셀커크 렉스', value: 'Selkirk Rex' },
  { label: '소말리', value: 'Somali' },
  { label: '스코티시 폴드', value: 'Scottish Fold' },
  { label: '스코티시 스트레이트', value: 'Scottish Straight' },
  { label: '스핑크스', value: 'Sphynx' },
  { label: '싱가푸라', value: 'Singapura' },
  { label: '스노우슈', value: 'Snowshoe' },
  { label: '사바나', value: 'Savannah' },
  { label: '소코케', value: 'Sokoke' },
  { label: '아라비안 마우', value: 'Arabian Mau' },
  { label: '아메리칸 밥테일', value: 'American Bobtail' },
  { label: '아메리칸 쇼트헤어', value: 'American Shorthair' },
  { label: '아메리칸 와이어헤어', value: 'American Wirehair' },
  { label: '아메리칸 컬', value: 'American Curl' },
  { label: '아비시니안', value: 'Abyssinian' },
  { label: '오리엔탈 쇼트헤어', value: 'Oriental Shorthair' },
  { label: '오리엔탈 롱헤어', value: 'Oriental Longhair' },
  { label: '오시캣', value: 'Ocicat' },
  { label: '유러피안', value: 'European Shorthair' },
  { label: '유러피안버미즈', value: 'European Burmese' },
  { label: '이집션마우', value: 'Egyptian Mau' },
  { label: '엑조틱', value: 'Exotic' },
  { label: '재패니즈 밥테일', value: 'Japanese Bobtail' },
  { label: '쵸시', value: 'Chausie' },
  { label: '카오마니', value: 'Korat' },
  { label: '컬러포인트쇼트헤어', value: 'Colorpoint Shorthair' },
  { label: '코니시 렉스', value: 'Cornish Rex' },
  { label: '코랫', value: 'Korat' },
  { label: '쿠리리안 밥테일', value: 'Kurilian Bobtail' },
  { label: '킴릭', value: 'Khmer' },
  { label: '타이', value: 'Thai' },
  { label: '터키시 반', value: 'Turkish Van' },
  { label: '터키시 앙고라', value: 'Turkish Angora' },
  { label: '통키니즈', value: 'Tonkinese' },
  { label: '토이거', value: 'Toyger' },
  { label: '토이밥', value: 'Toybob' },
  { label: '페르시안', value: 'Persian' },
  { label: '픽시 밥', value: 'Pixie-bob' },
  { label: '피터볼드', value: 'Peterbald' },
  { label: '하바나브라운', value: 'Havana Brown' },
  { label: '히말라얀', value: 'Himalayan' },
];
