spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petdio?autoReconnect=true&useSSL=false
    username: root
    password: ssafy

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081

oauth2:
  client:
    registration:
      kakao:
        client-id: 5cbf09b95a19614cdacf0809b098a3ad
        client-secret: iHq2IBRtKDzhWBQHnnENwAA02NeMZHfz
        redirect-uri: http://localhost:8081/kakao/login
        authorization-grant-type: authorization_code
        client-authentication-method: client_secret_post
        client-name: Kakao
        scope:
          - profile_nickname
          - profile_image
          - account_email
        authorization-uri: https://kauth.kakao.com/oauth/authorize  # 인가 코드
        token-uri: https://kauth.kakao.com/oauth/token              # 토큰 받기
        user-info-uri: https://kapi.kakao.com/v2/user/me

        user-name-attribute: id

jwt:
  secret: asdfghjklqwertyuiopzxcvbnmasdfasdfweasdfwbzzgoooodItstootireddgdsasdfsawherhdsfbdfsgsadfsadvsvethegwfsdavbdfh
  token-validity-in-milliseconds: 100000000
  refresh-token: 987654321987654321
  refresh-token-limit-days: 14